service: serverless-first-project

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3
  httpApi:
    cors: true
plugins:
  - serverless-offline
functions:
  handler:
    handler: index.handler
    description: First lambda sample
    events:
      - httpApi:
          path: /
          method: get
